services:
  webui:
    build: .
    networks:
      - proxy
    volumes:
      - ./models:/app/models
      - ./configs:/app/configs
      - ./repositories:/app/repositories
      - ./outputs:/app/outputs
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia

networks:
  proxy:
    external: true
