services:
  webui:
    build: .
    volumes:
      - ./models:/app/models
      - ./configs:/app/configs
      - ./repositories:/app/repositories
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu, utility]
              driver: nvidia

networks:
  proxy:
    external: true