services:
  webui:
    build: .
    ports:
      - 7860:7860
    volumes:
      - ./models:/app/models
      - ./configs:/app/configs
      - ./repositories:/app/repositories
      - ./output:/app/output
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia

networks:
  proxy:
    external: true
